import dimensions from "../data/image-dimensions.json";

export interface ImageDimensions {
  width: number;
  height: number;
}

const MAP: Readonly<Record<string, ImageDimensions>> = dimensions;

/**
 * Intrinsic size of a site-relative image referenced by content, so article
 * images can carry width/height and reserve their space before loading.
 * Generated by scripts/generate-image-dimensions.mjs; unknown sources
 * (external URLs, images added since the last run) return undefined.
 */
export function getImageDimensions(src: unknown): ImageDimensions | undefined {
  if (typeof src !== "string" || !Object.hasOwn(MAP, src)) return undefined;
  return MAP[src];
}
